### PR TITLE
Implement fix by looking at filtered length for hasMessages

### LINKED ISSUE #28: Bug: Severity filtering will still comment even if empty
Found a bug in my implementation for https://github.com/azu/security-alert/issues/21
If the SARIF has no "error" severities but you filter by severity error, it will still add a comment, without any findings inside...
This should fail silently/return

### PR DESCRIPTION
**Pull request by Gby56**
Fixes #28 
Tested with a new test `simple-semgrep-juiceshop-error-only-empty`, the cli returns:
```
Some comments were not posted, reasons will be included
Markdown extracted from SARIF was empty
```

### CODE REVIEW

**Comment by Gby56** [comment]
@azu can I merge ?

File: packages/sarif-to-markdown/src/sarif-to-markdown.ts [hunk 1]
```diff
@@ -229,7 +229,7 @@ export const sarifToMarkdown = (options: sarifFormatterOptions): ((sarifLog: Log
             If pass the scan, results is empty array
             */
             const results =
-                run.results && run.results.length > 0
+                run.results && run.results.length > 0 && Object.keys(filteredResults).length > 0
```
Comment (azu) [inline packages/sarif-to-markdown/src/sarif-to-markdown.ts:232]: We can defined a variable instead of repeating the statment.
```js
const hasMessage = run.results && run.results.length > 0 && Object.keys(filteredResults).length > 0;
// or 
const hasResult = run.results && run.results.length > 0 && Object.keys(filteredResults).length > 0;
```

Comment (Gby56) [reply packages/sarif-to-markdown/src/sarif-to-markdown.ts]: Just pushed a commit with the constant.
There was a difference though, with these 2 conditions:
`run.results && run.results.length > 0 && Object.keys(filteredResults).length > 0`
vs
`run.results?.length !== 0 && Object.keys(filteredResults).length !== 0`

**Review by azu — APPROVED** [review]
LGTM

**Comment by azu** [comment]
Release https://github.com/azu/security-alert/releases/tag/v1.10.3

**Comment by Gby56** [comment]
Thanks !
